#### Data Dictionary

* Survival	0 = No, 1 = Yes
* pclass =>	Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd)
* sex = Sex
* Age => Age in years
* sibsp => # of siblings / spouses aboard the Titanic
* parch => # of parents / children aboard the Titanic
* ticket => Ticket number	
* fare => Passenger fare	
* cabin => Cabin number
* embarked => Port of Embarkation (C = Cherbourg, Q = Queenstown, S = Southampton)



#### Variable Notes
#### pclass: A proxy for socio-economic status (SES)
* 1st = Upper
* 2nd = Middle
* 3rd = Lower



#### age: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5



#### sibsp: The dataset defines family relations in this way...
* Sibling = brother, sister, stepbrother, stepsister
* Spouse = husband, wife (mistresses and fiancés were ignored)



#### parch: The dataset defines family relations in this way...
* Parent = mother, father
* Child = daughter, son, stepdaughter, stepson
* Some children travelled only with a nanny, therefore parch=0 for them.




In [1]:
# read csv files

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# -- Feature Engineering --

In [2]:
df = pd.read_csv('train.csv')

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
test_df = pd.read_csv('test.csv')
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [4]:
surv_col = df.iloc[:,1]
surv_col.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [5]:
train_df = df.iloc[:,2:]
train_df.head()

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S

In [6]:
pessengerId = test_df.iloc[:,0]
pessengerId.head()

0    892
1    893
2    894
3    895
4    896
Name: PassengerId, dtype: int64

In [7]:
test_df.drop(['PassengerId'],axis=1,inplace=True)

test_df.head()

Pclass                                          Name     Sex   Age  SibSp  \
0       3                              Kelly, Mr. James    male  34.5      0   
1       3              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2       2                     Myles, Mr. Thomas Francis    male  62.0      0   
3       3                              Wirz, Mr. Albert    male  27.0      0   
4       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1   

   Parch   Ticket     Fare Cabin Embarked  
0      0   330911   7.8292   NaN        Q  
1      0   363272   7.0000   NaN        S  
2      0   240276   9.6875   NaN        Q  
3      0   315154   8.6625   NaN        S  
4      1  3101298  12.2875   NaN        S

In [8]:
train_df.head()

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S

In [9]:
concated_df = pd.concat([train_df,test_df])

concated_df.head()

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S

In [10]:
concated_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 10 columns):
Pclass      1309 non-null int64
Name        1309 non-null object
Sex         1309 non-null object
Age         1046 non-null float64
SibSp       1309 non-null int64
Parch       1309 non-null int64
Ticket      1309 non-null object
Fare        1308 non-null float64
Cabin       295 non-null object
Embarked    1307 non-null object
dtypes: float64(2), int64(3), object(5)
memory usage: 112.5+ KB


In [11]:
from sklearn import preprocessing as prep

# Label Encoding for Sex Column

In [12]:
le = prep.LabelEncoder()

concated_df.Sex =le.fit_transform(concated_df.Sex)

df.Sex[0:10]

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: object

In [13]:
concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S

In [14]:
concated_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 10 columns):
Pclass      1309 non-null int64
Name        1309 non-null object
Sex         1309 non-null int32
Age         1046 non-null float64
SibSp       1309 non-null int64
Parch       1309 non-null int64
Ticket      1309 non-null object
Fare        1308 non-null float64
Cabin       295 non-null object
Embarked    1307 non-null object
dtypes: float64(2), int32(1), int64(3), object(4)
memory usage: 107.4+ KB


### On the some columns, there are some missing values. Firstly I need to fill that columns

In [15]:
embarked = concated_df['Embarked'].fillna('0')

embarked.unique()

array(['S', 'C', 'Q', '0'], dtype=object)

# Label Encoding for Embarked Column

In [16]:
concated_df.Embarked = le.fit_transform(embarked)

concated_df.Embarked.unique()

array([3, 1, 2, 0], dtype=int64)

In [17]:
concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare Cabin  Embarked  
0      1      0         A/5 21171   7.2500   NaN         3  
1      1      0          PC 17599  71.2833   C85         1  
2      0      0  STON/O2. 3101282   7.9250   NaN         3  
3      1      0            113803  53.1000  C123         3  
4      0      0            373450   8.0500   NaN         3

In [18]:
concated_df.tail()

Pclass                          Name  Sex   Age  SibSp  Parch  \
413       3            Spector, Mr. Woolf    1   NaN      0      0   
414       1  Oliva y Ocana, Dona. Fermina    0  39.0      0      0   
415       3  Saether, Mr. Simon Sivertsen    1  38.5      0      0   
416       3           Ware, Mr. Frederick    1   NaN      0      0   
417       3      Peter, Master. Michael J    1   NaN      1      1   

                 Ticket      Fare Cabin  Embarked  
413           A.5. 3236    8.0500   NaN         3  
414            PC 17758  108.9000  C105         1  
415  SOTON/O.Q. 3101262    7.2500   NaN         3  
416              359309    8.0500   NaN         3  
417                2668   22.3583   NaN         1

In [19]:
concated_df.dtypes

Pclass        int64
Name         object
Sex           int32
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked      int32
dtype: object

In [20]:
print( 'Pclass:' ,concated_df.Pclass.unique())
print( 'Sex:' ,concated_df.Sex.unique())
print( 'SibSp:' ,concated_df.SibSp.unique())
print( 'Parch:' ,concated_df.Parch.unique())
print( 'Embarked:' ,concated_df.Embarked.unique())

Pclass: [3 1 2]
Sex: [1 0]
SibSp: [1 0 3 4 2 5 8]
Parch: [0 1 2 5 3 4 6 9]
Embarked: [3 1 2 0]


### I will remove Cabin columns

In [21]:
concated_df.drop(['Cabin'],axis=1,inplace=True)

concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare  Embarked  
0      1      0         A/5 21171   7.2500         3  
1      1      0          PC 17599  71.2833         1  
2      0      0  STON/O2. 3101282   7.9250         3  
3      1      0            113803  53.1000         3  
4      0      0            373450   8.0500         3

In [22]:
NameSplit = concated_df.Name.str.split('[,.]')

NameSplit.head()

0                          [Braund,  Mr,  Owen Harris]
1    [Cumings,  Mrs,  John Bradley (Florence Briggs...
2                           [Heikkinen,  Miss,  Laina]
3     [Futrelle,  Mrs,  Jacques Heath (Lily May Peel)]
4                         [Allen,  Mr,  William Henry]
Name: Name, dtype: object

In [23]:
titles = [str.strip(name[1]) for name in NameSplit.values]
titles[:10]

['Mr', 'Mrs', 'Miss', 'Mrs', 'Mr', 'Mr', 'Mr', 'Master', 'Mrs', 'Mrs']

In [24]:
# new feature

concated_df['Title'] = titles

concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare  Embarked Title  
0      1      0         A/5 21171   7.2500         3    Mr  
1      1      0          PC 17599  71.2833         1   Mrs  
2      0      0  STON/O2. 3101282   7.9250         3  Miss  
3      1      0            113803  53.1000         3   Mrs  
4      0      0            373450   8.0500         3    Mr

In [25]:
concated_df.Title.unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the Countess',
       'Jonkheer', 'Dona'], dtype=object)

In [26]:
# useless words: I will combine Mademoiselle and Madame into a single type

concated_df.Title.values[concated_df.Title.isin(['Mme', 'Mmle'])] = 'Mmle'

In [27]:
# keep reducing

concated_df.Title.values[concated_df.Title.isin(['Capt', 'Don', 'Major', 'Sir'])] = 'Sir'
concated_df.Title.values[concated_df.Title.isin(['Dona', 'Lady', 'the Countess', 'Jonkheer'])] = 'Lady'

In [28]:
concated_df.Title.unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Sir', 'Rev', 'Dr', 'Mmle', 'Ms',
       'Lady', 'Mlle', 'Col'], dtype=object)

In [29]:
# label encode new feature too

concated_df.Title = le.fit_transform(concated_df.Title)
concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare  Embarked  Title  
0      1      0         A/5 21171   7.2500         3      7  
1      1      0          PC 17599  71.2833         1      8  
2      0      0  STON/O2. 3101282   7.9250         3      4  
3      1      0            113803  53.1000         3      8  
4      0      0            373450   8.0500         3      7

In [30]:
# new feature is family size
# number of spouses and siblings and oneself is family size

concated_df['FamilySize'] = concated_df.SibSp.values + concated_df.Parch.values + 1

In [31]:
concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare  Embarked  Title  FamilySize  
0      1      0         A/5 21171   7.2500         3      7           2  
1      1      0          PC 17599  71.2833         1      8           2  
2      0      0  STON/O2. 3101282   7.9250         3      4           1  
3      1      0            113803  53.1000         3      8           2  
4      0      0            373450   8.0500         3      7           1

In [32]:
surnames = [str.strip(name[0]) for name in NameSplit]
surnames[:10]

['Braund',
 'Cumings',
 'Heikkinen',
 'Futrelle',
 'Allen',
 'Moran',
 'McCarthy',
 'Palsson',
 'Johnson',
 'Nasser']

In [33]:
concated_df['Surname'] = surnames
concated_df['FamilyID'] = concated_df.Surname.str.cat(concated_df.FamilySize.astype(str),sep='')
concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare  Embarked  Title  FamilySize  \
0      1      0         A/5 21171   7.2500         3      7           2   
1      1      0          PC 17599  71.2833         1      8           2   
2      0      0  STON/O2. 3101282   7.9250         3      4           1   
3      1      0            113803  53.1000         3      8           2   
4      0      0            373450   8.0500         3      7           1   

     Surname    FamilyID  
0     Braund     Braund2  
1    Cumings    Cumings2  
2  Heikkinen  Heikkinen1  
3   Futrelle   Futrelle2  
4      Allen      Allen1

In [34]:
# I will mark if any family id as small if family size is less than or equal to 2

concated_df.FamilyID.values[concated_df.FamilySize.values <= 2] = 'Small'

concated_df.head()

Pclass                                               Name  Sex   Age  \
0       3                            Braund, Mr. Owen Harris    1  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
2       3                             Heikkinen, Miss. Laina    0  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
4       3                           Allen, Mr. William Henry    1  35.0   

   SibSp  Parch            Ticket     Fare  Embarked  Title  FamilySize  \
0      1      0         A/5 21171   7.2500         3      7           2   
1      1      0          PC 17599  71.2833         1      8           2   
2      0      0  STON/O2. 3101282   7.9250         3      4           1   
3      1      0            113803  53.1000         3      8           2   
4      0      0            373450   8.0500         3      7           1   

     Surname FamilyID  
0     Braund    Small  
1    Cumings    Small  
2  Heikkinen    Small  
3   Futrelle    Small  
4      Allen    Small

In [35]:
# check up the frequency of family ids
concated_df.FamilyID.value_counts()

Small                1025
Sage11                 11
Andersson7              9
Goodwin8                8
Asplund7                7
Skoog6                  6
Rice6                   6
Panula6                 6
Fortune6                6
Palsson5                5
Lefebre5                5
Ryerson5                5
Ford5                   5
Davies3                 5
Johnston4               4
Becker4                 4
Laroche4                4
West4                   4
Herman4                 4
Dean4                   4
Allison4                4
Baclini4                4
Carter4                 4
Brown3                  4
Caldwell3               3
Danbom3                 3
Peter3                  3
McCoy3                  3
Rosblom3                3
Klasen3                 3
                     ... 
Lahtinen3               2
Hocking4                2
Frolicher-Stehli3       2
Kink3                   2
Kink-Heilmann3          2
Hamalainen3             2
Gustafsson3             2
Appleton3   

## There are too many family ids with few family members. maybe some families had different last names. I'll clean this.

In [36]:
freq = list(dict(zip(concated_df.FamilyID.value_counts().index.tolist(), concated_df.FamilyID.value_counts().values)).items())

type(freq)

list

In [37]:
freq = np.array(freq)

freq[:10]

array([['Small', '1025'],
       ['Sage11', '11'],
       ['Andersson7', '9'],
       ['Goodwin8', '8'],
       ['Asplund7', '7'],
       ['Skoog6', '6'],
       ['Rice6', '6'],
       ['Panula6', '6'],
       ['Fortune6', '6'],
       ['Palsson5', '5']], dtype='<U17')

In [38]:
freq.shape

(97, 2)

In [39]:
# select the family ids with frequency of 2 or less
freq[freq[:,1].astype(int) <= 2].shape

(36, 2)

In [40]:
freq = freq[freq[:,1].astype(int) <= 2]

In [41]:
# I'll assign 'Small' for those
concated_df.FamilyID.values[concated_df.FamilyID.isin(freq[:,0])] = 'Small'
concated_df.FamilyID.value_counts()

Small            1074
Sage11             11
Andersson7          9
Goodwin8            8
Asplund7            7
Rice6               6
Skoog6              6
Fortune6            6
Panula6             6
Lefebre5            5
Palsson5            5
Ryerson5            5
Ford5               5
Davies3             5
Brown3              4
Becker4             4
Baclini4            4
Dean4               4
Laroche4            4
West4               4
Allison4            4
Johnston4           4
Herman4             4
Carter4             4
Sandstrom3          3
Quick3              3
Compton3            3
Samaan3             3
Thayer3             3
Peacock3            3
                 ... 
McCoy3              3
Klasen3             3
Dodge3              3
Caldwell3           3
Boulos3             3
Wick3               3
Bourke3             3
Elias3              3
Crosby3             3
van Billiard3       3
Hart3               3
Taussig3            3
Abbott3             3
Touma3              3
Coutts3   

In [42]:
# label encoding for family id

concated_df.FamilyID = le.fit_transform(concated_df.FamilyID)
concated_df.FamilyID.unique()

array([50, 38, 28, 48,  2, 43,  3, 22, 31, 47, 39, 57, 24, 49, 35,  9, 21,
       17, 27, 41,  6, 37, 60, 46, 23, 30, 32,  5,  7, 11, 44, 54, 52,  0,
        1, 34, 45, 25, 58, 51, 13, 20, 59, 36, 10, 19, 55, 15, 18,  4, 42,
       14, 16, 53, 26,  8, 56, 29, 33, 12, 40], dtype=int64)

In [43]:
# I will choose usefull features
concated_reduce = concated_df[[
    'Pclass', 'Sex', 'Age', 'SibSp',
    'Parch', 'Fare', 'Title', 'Embarked', 'FamilySize',
    'FamilyID']]

concated_reduce.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Title  Embarked  FamilySize  \
0       3    1  22.0      1      0   7.2500      7         3           2   
1       1    0  38.0      1      0  71.2833      8         1           2   
2       3    0  26.0      0      0   7.9250      4         3           1   
3       1    0  35.0      1      0  53.1000      8         3           2   
4       3    1  35.0      0      0   8.0500      7         3           1   

   FamilyID  
0        50  
1        50  
2        50  
3        50  
4        50

In [44]:
concated_reduce.Age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  , 22.5 ,
       18.5 , 67.  , 76.  , 26.5 , 60.5 , 11.5 ,  0.33,  0.17, 38.5 ])

In [45]:
concated_reduce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 10 columns):
Pclass        1309 non-null int64
Sex           1309 non-null int32
Age           1046 non-null float64
SibSp         1309 non-null int64
Parch         1309 non-null int64
Fare          1308 non-null float64
Title         1309 non-null int32
Embarked      1309 non-null int32
FamilySize    1309 non-null int64
FamilyID      1309 non-null int32
dtypes: float64(2), int32(4), int64(4)
memory usage: 92.0 KB


## There are missing values on Age Column. Therefore I will fill taking Median

In [46]:
concated_reduce['Age'].fillna(concated_reduce['Age'].median(), inplace=True)
concated_reduce['Fare'].fillna(concated_reduce['Fare'].median(), inplace=True)

In [47]:
concated_reduce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 10 columns):
Pclass        1309 non-null int64
Sex           1309 non-null int32
Age           1309 non-null float64
SibSp         1309 non-null int64
Parch         1309 non-null int64
Fare          1309 non-null float64
Title         1309 non-null int32
Embarked      1309 non-null int32
FamilySize    1309 non-null int64
FamilyID      1309 non-null int32
dtypes: float64(2), int32(4), int64(4)
memory usage: 92.0 KB


# So, That Dataset (concated_reduce) is ready for spliting as Train and Test values.

In [48]:
train_final = concated_reduce.iloc[:891].copy()
test_final = concated_reduce.iloc[891:].copy()

In [49]:
train_final.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Title  Embarked  FamilySize  \
0       3    1  22.0      1      0   7.2500      7         3           2   
1       1    0  38.0      1      0  71.2833      8         1           2   
2       3    0  26.0      0      0   7.9250      4         3           1   
3       1    0  35.0      1      0  53.1000      8         3           2   
4       3    1  35.0      0      0   8.0500      7         3           1   

   FamilyID  
0        50  
1        50  
2        50  
3        50  
4        50

In [50]:
test_final.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Title  Embarked  FamilySize  \
0       3    1  34.5      0      0   7.8292      7         2           1   
1       3    0  47.0      1      0   7.0000      8         3           2   
2       2    1  62.0      0      0   9.6875      7         2           1   
3       3    1  27.0      0      0   8.6625      7         3           1   
4       3    0  22.0      1      1  12.2875      8         3           3   

   FamilyID  
0        50  
1        50  
2        50  
3        50  
4        50

## At the outset, I splited some columns on the dataset. Now I will use that columns for creating Train dataset

In [51]:
X = train_final.values

X

array([[ 3.,  1., 22., ...,  3.,  2., 50.],
       [ 1.,  0., 38., ...,  1.,  2., 50.],
       [ 3.,  0., 26., ...,  3.,  1., 50.],
       ...,
       [ 3.,  0., 28., ...,  3.,  4., 29.],
       [ 1.,  1., 26., ...,  1.,  1., 50.],
       [ 3.,  1., 32., ...,  2.,  1., 50.]])

In [52]:
y = surv_col.values

y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [53]:
X.shape

(891, 10)

In [54]:
y.shape

(891,)

In [55]:
test_data = test_final.values

test_data

array([[ 3. ,  1. , 34.5, ...,  2. ,  1. , 50. ],
       [ 3. ,  0. , 47. , ...,  3. ,  2. , 50. ],
       [ 2. ,  1. , 62. , ...,  2. ,  1. , 50. ],
       ...,
       [ 3. ,  1. , 38.5, ...,  3. ,  1. , 50. ],
       [ 3. ,  1. , 28. , ...,  3. ,  1. , 50. ],
       [ 3. ,  1. , 28. , ...,  1. ,  3. , 41. ]])

# Creating Neural Network with Keras

In [56]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [57]:
model = Sequential()

model.add(Dense(32, init = 'uniform', activation='relu', input_dim = 10))
model.add(Dense(64, init = 'uniform', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, init = 'uniform', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(12, init = 'uniform', activation='relu'))
model.add(Dense(1, init = 'uniform', activation='sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [58]:
model.fit(X,y, epochs=500, batch_size = 64, verbose = 1)

Epoch 1/500
891/891 [==============================] - 2s 2ms/step - loss: 0.6921 - acc: 0.5926
Epoch 2/500
891/891 [==============================] - 0s 63us/step - loss: 0.6829 - acc: 0.6162
Epoch 3/500
891/891 [==============================] - 0s 67us/step - loss: 0.6476 - acc: 0.6386
Epoch 4/500
891/891 [==============================] - 0s 63us/step - loss: 0.6148 - acc: 0.6723
Epoch 5/500
891/891 [==============================] - 0s 65us/step - loss: 0.6100 - acc: 0.6801
Epoch 6/500
891/891 [==============================] - 0s 64us/step - loss: 0.6072 - acc: 0.6779
Epoch 7/500
891/891 [==============================] - 0s 62us/step - loss: 0.5968 - acc: 0.6869
Epoch 8/500
891/891 [==============================] - 0s 64us/step - loss: 0.5935 - acc: 0.6824
Epoch 9/500
891/891 [==============================] - 0s 62us/step - loss: 0.5950 - acc: 0.6869
Epoch 10/500
891/891 [==============================] - 0s 67us/step - loss: 0.5908 - acc: 0.6925
Epoch 11/500
891/891 [========

891/891 [==============================] - 0s 59us/step - loss: 0.4221 - acc: 0.8126
Epoch 85/500
891/891 [==============================] - 0s 101us/step - loss: 0.4174 - acc: 0.8070
Epoch 86/500
891/891 [==============================] - 0s 58us/step - loss: 0.4292 - acc: 0.8171
Epoch 87/500
891/891 [==============================] - 0s 57us/step - loss: 0.4198 - acc: 0.8092
Epoch 88/500
891/891 [==============================] - 0s 57us/step - loss: 0.4396 - acc: 0.7935
Epoch 89/500
891/891 [==============================] - 0s 60us/step - loss: 0.4139 - acc: 0.8215
Epoch 90/500
891/891 [==============================] - 0s 64us/step - loss: 0.4196 - acc: 0.8159
Epoch 91/500
891/891 [==============================] - 0s 69us/step - loss: 0.4204 - acc: 0.8114
Epoch 92/500
891/891 [==============================] - 0s 59us/step - loss: 0.4191 - acc: 0.8238
Epoch 93/500
891/891 [==============================] - 0s 62us/step - loss: 0.4117 - acc: 0.8148
Epoch 94/500
891/891 [==========

891/891 [==============================] - 0s 62us/step - loss: 0.3813 - acc: 0.8373
Epoch 168/500
891/891 [==============================] - 0s 63us/step - loss: 0.3819 - acc: 0.8429
Epoch 169/500
891/891 [==============================] - 0s 64us/step - loss: 0.3835 - acc: 0.8339
Epoch 170/500
891/891 [==============================] - 0s 62us/step - loss: 0.3820 - acc: 0.8316
Epoch 171/500
891/891 [==============================] - 0s 63us/step - loss: 0.3841 - acc: 0.8316
Epoch 172/500
891/891 [==============================] - 0s 59us/step - loss: 0.3855 - acc: 0.8339
Epoch 173/500
891/891 [==============================] - 0s 65us/step - loss: 0.3845 - acc: 0.8339
Epoch 174/500
891/891 [==============================] - 0s 60us/step - loss: 0.3761 - acc: 0.8350
Epoch 175/500
891/891 [==============================] - 0s 62us/step - loss: 0.3778 - acc: 0.8429
Epoch 176/500
891/891 [==============================] - 0s 60us/step - loss: 0.3847 - acc: 0.8305
Epoch 177/500
891/891 [=

891/891 [==============================] - 0s 60us/step - loss: 0.3669 - acc: 0.8507
Epoch 250/500
891/891 [==============================] - 0s 63us/step - loss: 0.3608 - acc: 0.8519
Epoch 251/500
891/891 [==============================] - 0s 62us/step - loss: 0.3602 - acc: 0.8462
Epoch 252/500
891/891 [==============================] - 0s 61us/step - loss: 0.3603 - acc: 0.8496
Epoch 253/500
891/891 [==============================] - 0s 63us/step - loss: 0.3527 - acc: 0.8451
Epoch 254/500
891/891 [==============================] - 0s 60us/step - loss: 0.3608 - acc: 0.8496
Epoch 255/500
891/891 [==============================] - 0s 62us/step - loss: 0.3608 - acc: 0.8474
Epoch 256/500
891/891 [==============================] - 0s 65us/step - loss: 0.3667 - acc: 0.8429
Epoch 257/500
891/891 [==============================] - 0s 62us/step - loss: 0.3483 - acc: 0.8451
Epoch 258/500
891/891 [==============================] - 0s 64us/step - loss: 0.3649 - acc: 0.8451
Epoch 259/500
891/891 [=

891/891 [==============================] - 0s 63us/step - loss: 0.3531 - acc: 0.8485
Epoch 332/500
891/891 [==============================] - 0s 73us/step - loss: 0.3466 - acc: 0.8586
Epoch 333/500
891/891 [==============================] - 0s 59us/step - loss: 0.3365 - acc: 0.8563
Epoch 334/500
891/891 [==============================] - 0s 71us/step - loss: 0.3452 - acc: 0.8474
Epoch 335/500
891/891 [==============================] - 0s 63us/step - loss: 0.3612 - acc: 0.8586
Epoch 336/500
891/891 [==============================] - 0s 72us/step - loss: 0.3381 - acc: 0.8664
Epoch 337/500
891/891 [==============================] - 0s 62us/step - loss: 0.3401 - acc: 0.8575
Epoch 338/500
891/891 [==============================] - 0s 60us/step - loss: 0.3666 - acc: 0.8485
Epoch 339/500
891/891 [==============================] - 0s 64us/step - loss: 0.3529 - acc: 0.8429
Epoch 340/500
891/891 [==============================] - 0s 65us/step - loss: 0.3433 - acc: 0.8653
Epoch 341/500
891/891 [=

891/891 [==============================] - 0s 62us/step - loss: 0.3472 - acc: 0.8608
Epoch 414/500
891/891 [==============================] - 0s 63us/step - loss: 0.3372 - acc: 0.8575
Epoch 415/500
891/891 [==============================] - 0s 64us/step - loss: 0.3460 - acc: 0.8496
Epoch 416/500
891/891 [==============================] - 0s 63us/step - loss: 0.3318 - acc: 0.8519
Epoch 417/500
891/891 [==============================] - 0s 60us/step - loss: 0.3322 - acc: 0.8653
Epoch 418/500
891/891 [==============================] - 0s 63us/step - loss: 0.3360 - acc: 0.8552
Epoch 419/500
891/891 [==============================] - 0s 60us/step - loss: 0.3145 - acc: 0.8608
Epoch 420/500
891/891 [==============================] - 0s 60us/step - loss: 0.3157 - acc: 0.8631
Epoch 421/500
891/891 [==============================] - 0s 63us/step - loss: 0.3343 - acc: 0.8664
Epoch 422/500
891/891 [==============================] - 0s 65us/step - loss: 0.3306 - acc: 0.8552
Epoch 423/500
891/891 [=

891/891 [==============================] - 0s 82us/step - loss: 0.2922 - acc: 0.8777
Epoch 496/500
891/891 [==============================] - 0s 93us/step - loss: 0.3066 - acc: 0.8721
Epoch 497/500
891/891 [==============================] - 0s 95us/step - loss: 0.3095 - acc: 0.8687
Epoch 498/500
891/891 [==============================] - 0s 78us/step - loss: 0.3132 - acc: 0.8642
Epoch 499/500
891/891 [==============================] - 0s 76us/step - loss: 0.2940 - acc: 0.8743
Epoch 500/500
891/891 [==============================] - 0s 72us/step - loss: 0.2992 - acc: 0.8586


In [59]:
pred = model.predict(test_data)

In [60]:
pred

array([[1.11169495e-01],
       [1.21524632e-01],
       [3.66419740e-02],
       [9.47236493e-02],
       [9.35877085e-01],
       [1.20214939e-01],
       [6.39111698e-01],
       [1.28485104e-02],
       [9.92011130e-01],
       [1.10142365e-01],
       [1.06151208e-01],
       [3.53682101e-01],
       [1.00000000e+00],
       [3.13808210e-02],
       [9.99999523e-01],
       [9.97650206e-01],
       [1.19112805e-01],
       [2.40320548e-01],
       [1.97116047e-01],
       [5.73110245e-02],
       [4.29393977e-01],
       [5.04933596e-01],
       [9.99948025e-01],
       [9.27370846e-01],
       [9.99999881e-01],
       [5.65859750e-02],
       [1.00000000e+00],
       [1.85420528e-01],
       [4.94262874e-01],
       [4.02560690e-03],
       [3.37668844e-02],
       [3.48023488e-04],
       [3.45645621e-02],
       [4.48268056e-02],
       [5.72877944e-01],
       [3.79957587e-01],
       [3.66254687e-01],
       [5.07590294e-01],
       [9.34331790e-02],
       [5.16609907e-01],


In [61]:
# convert to integer
outputBin = np.zeros(0)
for i in pred:
    
    if i <= .5:
        
        outputBin = np.append(outputBin, 0)
    else:
        
        outputBin = np.append(outputBin, 1)
output = np.array(outputBin).astype(int)

In [62]:
output

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [63]:
d = {'PassengerId':pessengerId, 'Survived':output}

In [64]:
final_df = pd.DataFrame(data=d)

In [65]:
final_df.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [66]:
final = final_df.to_csv('new_result.csv',index=False) #convert to csv file

final

# Random Forest Classifier

In [67]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=350, max_depth=15, random_state=42)

print("train accuracy: {} ".format(rf.fit(X, y).score(X, y)))


train accuracy: 0.9741863075196409 


In [68]:
rf_pred = rf.predict(test_data)

In [69]:
rf_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [70]:
r = {'PassengerId':pessengerId, 'Survived':rf_pred}

In [71]:
final_rf = pd.DataFrame(data=r)

In [72]:
final_rf.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [73]:
final_rf = final_df.to_csv('random_forest_result.csv',index=False) #convert to csv file

final_rf